name: Test Secrets Expansion

on:
  workflow_dispatch:

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.DEV_AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}"
      S3_BUCKET: "${{ secrets.S3_BUCKET }}"
      CLOUDFRONT_ID: "${{ secrets.CLOUDFRONT_ID }}"
    steps:
      - name: Print Secrets in Run
        run: |
          echo "Testing Secrets Expansion..."
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "S3_BUCKET: $S3_BUCKET"
          echo "CLOUDFRONT_ID: $CLOUDFRONT_ID"

      - name: Simulate S3 Upload and CloudFront Invalidation
        run: |
          echo "Uploading test-file.txt to S3 bucket: $S3_BUCKET"
          echo "aws s3 cp test-file.txt s3://$S3_BUCKET/"
          
          if [ -n "$CLOUDFRONT_ID" ]; then
            echo "Updating CloudFront distribution: $CLOUDFRONT_ID"
            echo "aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'"
          else
            echo "CLOUDFRONT_ID is not set. Skipping CloudFront invalidation."
          fi
