name: Test PR Workflow (No Deploy)

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action: Deploy (spin up) or Cleanup (destroy)"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - cleanup

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.pull_request.number || github.run_id }}
  S3_BUCKET_NAME: ${{ github.event.repository.name }}-${{ github.event.pull_request.number || github.run_id }}-dynamic-env
  DYNAMIC_ENVIRONMENT_URL: ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number || github.run_id }}.qa.cookunity.com

jobs:
  deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed' || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulating AWS Credentials Configuration (Skipping real AWS setup)
        run: echo "✅ AWS Credentials Configured (Simulated)"

      - name: Simulating S3 Bucket Creation
        run: |
          echo "✅ Simulated S3 Bucket Created: ${S3_BUCKET_NAME}"
          echo "✅ Simulated File Upload to S3"

      - name: Simulating CloudFront Distribution
        run: echo "✅ Simulated CloudFront Distribution Creation"

      - name: Simulating Route 53 DNS Setup
        run: echo "✅ Simulated Route 53 DNS Record Creation for ${DYNAMIC_ENVIRONMENT_URL}"

      - name: Post Comment on PR (Simulated)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚀 **(Test) Dynamic Environment Simulated!**\n🔗 Would be available at: https://${{ env.DYNAMIC_ENVIRONMENT_URL }}"
            })

  cleanup:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'cleanup'
    runs-on: ubuntu-latest
    #needs: deploy
    steps:
      - name: Simulating AWS Credentials Configuration (Skipping real AWS setup)
        run: echo "✅ AWS Credentials Configured (Simulated)"

      - name: Simulating S3 Bucket Deletion
        run: echo "✅ Simulated S3 Bucket Deletion for ${S3_BUCKET_NAME}"

      - name: Simulating CloudFront Distribution Removal
        run: echo "✅ Simulated CloudFront Distribution Removal"

      - name: Simulating Route 53 DNS Record Deletion
        run: echo "✅ Simulated Route 53 DNS Record Deletion for ${DYNAMIC_ENVIRONMENT_URL}"

      - name: Post Cleanup Comment on PR (Simulated)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🧹 **(Test) Dynamic Environment Cleanup Simulated!**"
            })