name: Test Secrets Expansion

on:
  workflow_dispatch:

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    env:
      SECRET_VALUE: "${{ secrets.MY_SECRET }}"
      OTHER_SECRET: "${{ secrets.OTHER_SECRET }}"
    steps:
      - name: Print Secrets in Run
        run: |
          echo "Testing Secrets Expansion..."
          echo "SECRET_VALUE is: $SECRET_VALUE"
          echo "OTHER_SECRET is: $OTHER_SECRET"

      - name: Use Secrets in a Command
        run: |
          if [ -z "$SECRET_VALUE" ]; then
            echo "❌ SECRET_VALUE is empty!"
            exit 1
          else
            echo "✅ SECRET_VALUE is set correctly!"
          fi
